import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import type { BankStatementContent } from '@/lib/schemas/source-document';

// HDFC-style statement variant (Phase 4, spec 16): mirrors a real bank
// export's column order — Date, Narration, Chq./Ref.No., Withdrawal,
// Deposit, Closing Balance — with the dense gridded look of an actual
// statement download. The Ref column is extracted deterministically from
// the narration's own reference token (bank narrations like
// "NEFT/N26040502/..." carry it); nothing is invented. Same
// BankStatementContent as the generic format.
const styles = StyleSheet.create({
  page: {
    padding: 28,
    fontSize: 8,
    fontFamily: 'Helvetica',
    color: '#1c1c1e',
  },
  bankName: {
    fontSize: 15,
    fontFamily: 'Helvetica-Bold',
    color: '#004c8f',
  },
  bankSub: {
    fontSize: 7.5,
    color: '#5c5c64',
    marginTop: 2,
  },
  headerRule: {
    borderBottom: '1.5pt solid #004c8f',
    marginTop: 8,
    marginBottom: 10,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  metaLabel: {
    fontFamily: 'Helvetica-Bold',
  },
  statementTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    marginTop: 8,
    marginBottom: 6,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#e8eef5',
    borderTop: '0.75pt solid #9a9aa2',
    borderBottom: '0.75pt solid #9a9aa2',
    fontFamily: 'Helvetica-Bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '0.5pt solid #dedee2',
  },
  colDate: { width: '11%', padding: 4 },
  colNarration: { width: '37%', padding: 4 },
  colRef: { width: '18%', padding: 4 },
  colDebit: { width: '11%', padding: 4, textAlign: 'right' },
  colCredit: { width: '11%', padding: 4, textAlign: 'right' },
  colBalance: { width: '12%', padding: 4, textAlign: 'right' },
  footer: {
    marginTop: 14,
    fontSize: 7,
    color: '#5c5c64',
  },
});

function formatAmount(amount: number | null): string {
  return amount === null ? '' : amount.toFixed(2);
}

// First reference-like token printed in the narration itself (4+ digit run,
// with any joined alphanumeric prefix/suffix), or blank when none exists.
function extractRef(narration: string): string {
  const match = narration.match(/[A-Za-z0-9/-]*\d{4,}[A-Za-z0-9/-]*/);
  return match ? match[0].slice(0, 20) : '';
}

type Props = {
  content: BankStatementContent;
};

export function BankStatementHdfcDocument({ content }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.bankName}>HDFC BANK</Text>
        <Text style={styles.bankSub}>We understand your world</Text>
        <View style={styles.headerRule} />

        <View style={styles.metaRow}>
          <Text>
            <Text style={styles.metaLabel}>Account Holder: </Text>
            {content.accountHolderName}
          </Text>
          <Text>
            <Text style={styles.metaLabel}>Statement Period: </Text>
            {content.period}
          </Text>
        </View>

        <Text style={styles.statementTitle}>Statement of Account</Text>

        <View style={styles.tableHeader}>
          <Text style={styles.colDate}>Date</Text>
          <Text style={styles.colNarration}>Narration</Text>
          <Text style={styles.colRef}>Chq./Ref.No.</Text>
          <Text style={styles.colDebit}>Withdrawal Amt.</Text>
          <Text style={styles.colCredit}>Deposit Amt.</Text>
          <Text style={styles.colBalance}>Closing Balance</Text>
        </View>
        {content.transactions.map((transaction, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.colDate}>{transaction.date}</Text>
            <Text style={styles.colNarration}>{transaction.narration}</Text>
            <Text style={styles.colRef}>{extractRef(transaction.narration)}</Text>
            <Text style={styles.colDebit}>{formatAmount(transaction.debit)}</Text>
            <Text style={styles.colCredit}>{formatAmount(transaction.credit)}</Text>
            <Text style={styles.colBalance}>{formatAmount(transaction.balance)}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          This is a computer generated statement for training practice and does not require a
          signature. Contents are generated by the AI Tutor, not issued by any bank.
        </Text>
      </Page>
    </Document>
  );
}
