import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import type { MonthEndNotesContent } from '@/lib/schemas/source-document';

// The owner's month-end notes sheet (documents mode): the instructions for
// journals and returns that have no third-party document. Text is the
// batch's own wording; this template only lays it out.
const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: 'Helvetica', color: '#232326', lineHeight: 1.4 },
  title: { fontSize: 16, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  subtitle: { fontSize: 10, color: '#5c5c64', marginBottom: 14, borderBottom: '1pt solid #DEDEE2', paddingBottom: 10 },
  intro: { marginBottom: 12 },
  note: { flexDirection: 'row', marginBottom: 10 },
  noteNumber: { width: 28, fontFamily: 'Helvetica-Bold' },
  noteBody: { flex: 1 },
  noteDate: { fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  footer: { marginTop: 24, fontSize: 8, color: '#5c5c64' },
});

type Props = { content: MonthEndNotesContent };

export function MonthEndNotesDocument({ content }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Month-end Notes</Text>
        <Text style={styles.subtitle}>
          {content.companyName}, {content.period}
        </Text>
        <Text style={styles.intro}>
          Adjustments and other entries to book this month that have no invoice or bank line of their own. Post each note as
          a voucher in the books, with a narration that says what it is for.
        </Text>
        {content.notes.map((note) => (
          <View key={note.number} style={styles.note}>
            <Text style={styles.noteNumber}>{note.number}.</Text>
            <View style={styles.noteBody}>
              <Text style={styles.noteDate}>{note.date}</Text>
              <Text>{note.text}</Text>
            </View>
          </View>
        ))}
        <Text style={styles.footer}>Generated by the AIA Academy for training practice.</Text>
      </Page>
    </Document>
  );
}
